a = input('Escreva algo: ')
print('Qual é o tipo ?', type(a))
print('Só tem espaços ?', a.isspace())
print('É um número ?', a.isalnum())
print('É do alfabeto ?', a.isalpha())
print('É um alfanumérico ?', a.isalnum())
print('É em maiúscula ?', a.isupper())
print('É em minúscula ?', a.islower())
print('É capitalizada ?'), a.istitle()
